import { Project } from '../../../packages/editor/src/state/types';

const project: Project = {
	title: 'Random Generators',
	author: 'Andor Polgar',
	description: '',
	codeBlocks: [
		{
			code: [
				'module lcg',
				'; Linear congruential ',
				'; generator',
				'',
				'const multiplier 1664525',
				'const increment 1013904223 ',
				'const modulus 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				' push multiplier',
				' push seed',
				' mul',
				' push increment',
				' add',
				' push modulus',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push modulus',
				' castToFloat',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
			x: 2,
			y: 1,
			isOpen: true,
		},
		{
			code: [
				'module XORShift',
				'',
				'int seed 69420',
				'float out',
				'',
				'push &seed',
				' push seed',
				' push seed',
				' push 13',
				' shiftLeft',
				' xor',
				'',
				' push seed',
				' push 17',
				' shiftRight',
				' xor',
				'',
				' push seed',
				' push 5',
				' shiftLeft',
				' xor',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push 2147483647',
				' castToFloat',
				' div',
				'store',
				'',
				'moduleEnd',
			],
			x: 74,
			y: 1,
			isOpen: true,
		},
		{
			code: [
				'module scope',
				'',
				'float* in &lcg.out',
				'float[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			x: 39,
			y: 1,
			isOpen: true,
		},
		{
			code: [
				'module scope2',
				'',
				'float* in &XORShift.out',
				'float[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			x: 109,
			y: 1,
			isOpen: true,
		},
	],
	viewport: { x: 0, y: 0 },
	rnbo: { patchers: {} },
	sampleRate: 50,
};

export default project;
